cos:
  client:
    host: xxxxxxxxxxxxxxxxxxxxxx # 存储桶域名
    secretId: xxxxxxxxxxxxxxxxxxxxx
    secretKey: xxxxxxxxxxxxxxxxxx
    region: xxxxxxxxxxxxxxxxxx
    bucket: xxxxxxxxxxxxxxxxxxxx # 存储桶名称
aliyun:
  apiKey: xxxxxxxxxxx
